### ISSUE TITLE
help

### ISSUE THREAD

**Issue by COCORONGZHENG** [XDChang/DCSliderView#1]
你好，如果我想设置节点等分，你现在好像不能做吧， 你demo里面的xx 和yy 都是根据屏幕宽度计算出来的，没有动态的去设置，能否告知啊，谢谢

**Comment by COCORONGZHENG** [comment]
楼主大人

**Comment by XDChang** [comment]
CGPoint pointR1 = CGPointMake(12 +(_yy+_xx*i)*i, 6);  (_yy+_xx*i) 这些你写个固定间距就行了，不一定要用 _yy  _xx 这参数。

**Comment by COCORONGZHENG** [comment]
谢谢回复，我在demo里面穿了下面title的数组进去是ok的，拖到项目里面，灰色的轨道没有画完，只画了一半感觉，请问一下大概知道什么原因么

**Comment by COCORONGZHENG** [comment]
楼主您好，DCSliderView 在初始化的时候frame的x值为你demo里面的10是正常的，如果我将x改为100，画出来的东西灰色轨道就有问题了，能麻烦您看一下是什么原因吗

**Comment by XDChang** [comment]
CGFloat gapX = self.frame.origin.x; 影响的代码是这一行，改为 CGFloat gapX = 10; 就可以了。需要的效果自己多调试下就好了。

**Comment by COCORONGZHENG** [comment]
偶 好的，谢谢
